name: opengen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  openapi_generator_annotations: ^6.1.0
  login_api:
    path: ./api/login_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  openapi_generator: ^6.1.0

flutter:
  uses-material-design: true
